### ISSUE TITLE
Blacklisted apps not working

### ISSUE THREAD

**Issue by rml9ty** [AnthoPakPak/PanCake#4]
Hi there,

I'm using version 2.2 on 15.1.1 rootless.

The black list filter for apps does not seem to be taking effect at all.

For instance, in Apollo it just messes with its own gestures immensely. If I disable PanCake injection with Choicy it works just fine, the black list within the tweak settings however does nothing unfortunately.

Best

P.S. bonus question: what do I have to blacklist, to still be able to trim videos in the standard iOS interface without it triggering the back swipe gesture. Because it's not 'Photos' (as far as I remember from back in the roomful days where the blacklist did work).

Love your tweaks btw. BlueFinder and PanCake are just such a necessity for me. ♥️

**Comment by AnthoPakPak** [comment]
Hello there,

On rootless jailbreaks PanCake prefs actually don't work. It was relying on Cephei to manage its prefs, and unfortunately Cephei is broken for sandboxed processes on rootless, leading to PanCake not applying user prefs in apps.
I should rewrite the prefs stuff to avoid using Cephei anymore, but I've unfortunately not had time to do so currently. For the time being, please use Choicy to blacklist apps instead of the PanCake built in setting.

Sorry about this! 😬

Regarding the question about trimming videos, blacklisting Photos from Choicy should work, let me know if it doesn't.

**Comment by rml9ty** [comment]
Thanks for the quick reply. I see. I suspect some people would love this info in the current changelog, even if you don't find the time to update it, as it's really not much work to do this with Choicy. But one just assumes that "updates for rootless" includes the settings that are offered. :)

Blacklisting photos also worked for trimming 👍

**Comment by AnthoPakPak** [comment]
You're right, I've just added a warning information on the depiction of PanCake Rootless. I wasn't expecting this situation to last, but it seems the fix to Cephei might be harder than expected.
Thanks for reminding me about this, hope you'll keep enjoying the tweak ✌️
